language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"


install:
    - python -mpip install tox
script:
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"

after_success:
    - if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
